// Memory verse of the week — 52 kid-friendly classics, selected by week number.
const MEMORY = [
{t:"God Made Everything",ref:"Genesis 1:1"},
{t:"The Lord Is My Shepherd",ref:"Psalms 23:1"},
{t:"When I'm Afraid",ref:"Psalms 56:3"},
{t:"This Is the Day",ref:"Psalms 118:24"},
{t:"A Lamp to My Feet",ref:"Psalms 119:105"},
{t:"His Love Endures Forever",ref:"Psalms 136:1"},
{t:"Be Still",ref:"Psalms 46:10"},
{t:"Wonderfully Made",ref:"Psalms 139:14"},
{t:"Trust in the Lord",ref:"Proverbs 3:5"},
{t:"A Friend Loves Always",ref:"Proverbs 17:17"},
{t:"Wings Like Eagles",ref:"Isaiah 40:31"},
{t:"Don't Be Afraid",ref:"Isaiah 41:10"},
{t:"Plans of Hope",ref:"Jeremiah 29:11"},
{t:"Let Your Light Shine",ref:"Matthew 5:16"},
{t:"Seek First",ref:"Matthew 6:33"},
{t:"The Golden Rule",ref:"Matthew 7:12"},
{t:"Love God Fully",ref:"Matthew 22:37"},
{t:"Always With You",ref:"Matthew 28:20"},
{t:"Come to Me",ref:"Matthew 11:28"},
{t:"All Things Are Possible",ref:"Matthew 19:26"},
{t:"Jesus Grew",ref:"Luke 2:52"},
{t:"Love Your Neighbor",ref:"Mark 12:31"},
{t:"God So Loved the World",ref:"John 3:16"},
{t:"Light of the World",ref:"John 8:12"},
{t:"The Good Shepherd",ref:"John 10:11"},
{t:"Love One Another",ref:"John 13:34"},
{t:"The Way, the Truth, the Life",ref:"John 14:6"},
{t:"The Vine and the Branches",ref:"John 15:5"},
{t:"Believe and Be Saved",ref:"Acts 16:31"},
{t:"All Have Sinned",ref:"Romans 3:23"},
{t:"While We Were Still Sinners",ref:"Romans 5:8"},
{t:"The Gift of God",ref:"Romans 6:23"},
{t:"All Things for Good",ref:"Romans 8:28"},
{t:"Overcome Evil with Good",ref:"Romans 12:21"},
{t:"Do It All for God's Glory",ref:"1 Corinthians 10:31"},
{t:"Love Is Patient",ref:"1 Corinthians 13:4"},
{t:"Everything in Love",ref:"1 Corinthians 16:14"},
{t:"Walk by Faith",ref:"2 Corinthians 5:7"},
{t:"Fruit of the Spirit",ref:"Galatians 5:22-23"},
{t:"Saved by Grace",ref:"Ephesians 2:8"},
{t:"Be Kind",ref:"Ephesians 4:32"},
{t:"Children, Obey",ref:"Ephesians 6:1"},
{t:"Rejoice Always",ref:"Philippians 4:4"},
{t:"Don't Worry — Pray",ref:"Philippians 4:6"},
{t:"I Can Do All Things",ref:"Philippians 4:13"},
{t:"God Will Provide",ref:"Philippians 4:19"},
{t:"Work for the Lord",ref:"Colossians 3:23"},
{t:"Give Thanks in Everything",ref:"1 Thessalonians 5:18"},
{t:"A Spirit of Power",ref:"2 Timothy 1:7"},
{t:"Jesus Never Changes",ref:"Hebrews 13:8"},
{t:"Quick to Listen",ref:"James 1:19"},
{t:"Cast Your Cares",ref:"1 Peter 5:7"}
];
