// Holiday special studies — override the daily rotation on their dates (see specialFor in index.html).
const SPECIALS = {
christmasEve: {label:"Christmas Eve Special",t:"The Night Before",ref:"Luke 2:4-7",
body:"No room in the inn, a borrowed stable, a feeding trough for a crib — the King of the universe arrived with no fanfare at all. God's biggest gift came quietly, to ordinary people, in an ordinary town. Tonight, the waiting of centuries turns into a baby's first cry.",
q:["Why do you think God chose such a humble arrival for Jesus?","Mary and Joseph had to trust God through a very inconvenient night. When has our family had to do that?","What are you most excited to celebrate tomorrow — and how do we keep Jesus at the center of it?"],
prayer:"Father, on this quiet night, make room in our hearts like there was no room in the inn. Thank You for sending Jesus.",
quiz:[{q:"Where was baby Jesus laid when he was born?",o:["A golden crib","A feeding trough (manger)","A royal bed"],c:1},{q:"Why were Mary and Joseph in Bethlehem?",o:["For a census (a big count of people)","For a wedding","For a vacation"],c:0},{q:"Who is the baby born this night?",o:["A new king of Rome","John the Baptist","Jesus, the Savior"],c:2}],
fun:"Turn off the lights, light one candle (with a grown-up), and sing 'Silent Night' together — just like that first quiet night."},
christmas: {label:"Christmas Day Special",t:"Good News of Great Joy",ref:"Luke 2:8-14",
body:"The birth announcement of the Son of God went to night-shift shepherds — not kings, not priests. 'Don't be afraid, for behold, I bring you good news of great joy which will be to all the people.' Christmas means the joy is for everyone, including everyone at this table.",
q:["Why do you think God sent angels to shepherds first instead of important people?","The angels said the good news is 'for all the people.' Who can we share some joy with today?","What's the best gift under the tree this morning — and how is Jesus better?"],
prayer:"Jesus, happy birthday and welcome. Thank You for being God's gift to us. Fill our home with great joy today.",
quiz:[{q:"Who heard the angels' announcement first?",o:["Kings in a palace","Shepherds watching sheep at night","Teachers in the temple"],c:1},{q:"What did the angel call the news about Jesus?",o:["Good news of great joy","A little secret","A warning"],c:0},{q:"Who is the joy of Christmas for?",o:["Only grown-ups","Only people back then","All the people — everyone"],c:2}],
fun:"Before opening a single present, everyone shouts the angels' words together: 'Glory to God in the highest!' Then celebrate big — it's Jesus' birthday!"},
newYear: {label:"New Year's Special",t:"A Fresh Start",ref:"Lamentations 3:22-23",
body:"A brand-new year, and the same faithful God. His mercies don't just come once a year — they're new every single morning, 365 fresh starts ahead. Today is for looking back at His faithfulness and forward with hope, together.",
q:["What is one thing God did for our family last year that we should remember out loud?","What's one thing each of us wants to grow in with God this year?","What could our family do together for God this year — one adventure, habit, or project?"],
prayer:"Faithful God, thank You for every mercy of last year. We give You this new one — lead our family through all of it.",
quiz:[{q:"How often are God's mercies new?",o:["Every morning","Once a year","Only on holidays"],c:0},{q:"What never comes to an end?",o:["Homework","The Lord's loving kindness","Winter"],c:1},{q:"What's the best way to start a new year?",o:["Worrying about it","Sleeping through January","Trusting the God whose mercies are new daily"],c:2}],
fun:"Make a family time capsule: everyone writes or draws one prayer for the new year. Seal the envelope and open it next New Year's Day!"},
goodFriday: {label:"Good Friday Special",t:"It Is Finished",ref:"John 19:28-30",
body:"Today is quiet on purpose. Jesus' final words from the cross — 'It is finished' — were not a cry of defeat but of completion: the rescue mission was done, the debt paid in full. We call this Friday 'good' because everything He suffered, He suffered for us.",
q:["Why do we call such a sad day 'Good' Friday?","'It is finished' — what exactly did Jesus finish?","How does it feel to know He did that for you, by name?"],
prayer:"Jesus, thank You for the cross. Today we remember what it cost You to love us. It is finished — and we are Yours.",
quiz:[{q:"What did Jesus say at the very end on the cross?",o:["'I'll be back'","'It is finished'","'Help me'"],c:1},{q:"Why is this Friday called 'good'?",o:["Because Jesus paid for our sins out of love","Because there's no school","Because it's almost Easter candy time"],c:0},{q:"Was the cross a defeat for Jesus?",o:["Yes, it was the end","Nobody knows","No — it was the rescue plan working"],c:2}],
fun:"Make a cross from two sticks and some string. Put it somewhere you'll see it Sunday morning — the story isn't over."},
easter: {label:"Easter Special",t:"He Is Risen!",ref:"Matthew 28:5-6",
body:"'He is not here, for he has risen, just like he said.' The tomb is empty — the biggest surprise in history, hiding in plain sight for three days. Because Jesus beat death, everything He promised is true, and everything sad will one day come untrue. Happy Easter — this is the day our whole faith stands on.",
q:["Imagine being the women at the tomb. What would you have felt seeing the stone rolled away?","'Just like he said' — why does it matter that Jesus predicted this?","Because Jesus is alive, what are we most looking forward to?"],
prayer:"Risen Jesus, You are alive! Fill our home with resurrection joy today and every day. Hallelujah!",
quiz:[{q:"What did the angel say at the tomb?",o:["'He is not here, for he has risen'","'Come back later'","'You're too early'"],c:0},{q:"How long was Jesus in the tomb?",o:["A whole year","Three days","One week"],c:1},{q:"What does the empty tomb prove?",o:["Someone moved him","Nothing much","Jesus beat death — He's alive"],c:2}],
fun:"Easter shout contest: one person says 'He is risen!' and everyone answers 'He is risen indeed!' — loudest round wins. Then hide and hunt something as a family, because the best find in history was an empty tomb."},
thanksgiving: {label:"Thanksgiving Special",t:"Enter with Thanksgiving",ref:"Psalms 100",
body:"Psalm 100 is the original Thanksgiving invitation: enter His gates with thanksgiving, His courts with praise. Before the turkey and the pie, this psalm reminds us who the feast points to — the God who made us, keeps us, and whose love endures forever.",
q:["Go around the table: what are you most thankful for this year — one big thing and one tiny thing?","Verse 3 says 'It is he who has made us, and we are his.' Why is belonging to God something to be thankful for?","Who outside our family could we bless or thank today?"],
prayer:"Father, every good thing on our table and in our lives came from You. We enter this day with thanksgiving and praise.",
quiz:[{q:"How does Psalm 100 say to enter God's gates?",o:["With thanksgiving","Very quietly","With a ticket"],c:0},{q:"How long does God's loving kindness last?",o:["Until December","Forever","One week"],c:1},{q:"What should we do 'to the Lord, all you lands'?",o:["Take a nap","Eat more pie","Shout for joy"],c:2}],
fun:"Thankful alphabet: go around the table naming things you're thankful for from A to Z. Can the family make it all the way?"}
};
